POST http://localhost:4002/products
content-type: application/json

{
    "name": "Caderno 96 folhas",
    "price": 15
}

### 

GET http://localhost:4002/products

###
GET http://localhost:4002/products/40db8cb1-b177-4689-8064-962a266f3ca2

###

PUT http://localhost:4002/products/711efc82-16f2-4d92-97fc-6a59ed849033
content-type: application/json

{
    "name": "Caderno 96 folhas preto",
    "price": 15
}

###
DELETE http://localhost:4002/products/d1b665ca-e218-40d5-921b-733022432df9